stages:
  land-anomalies:
    cmd:
      - mkdir -p data/raw
      - curl -L -o data/raw/land-anomalies.zip https://landslide-big-data-2425.s3.eu-central-1.amazonaws.com/land-anomalies.zip
      - unzip -qq -o data/raw/land-anomalies.zip -d data/raw
      - rm data/raw/land-anomalies.zip
    outs:
      - data/raw/land-anomalies