stages:
  L4S:
    cmd:
      - python scripts/data_prepare_L4S.py --src data/raw/L4S --dst data/processed/L4S
      - python scripts/data_prepare_config.py --dataset data/processed/L4S
    deps:
      - scripts/data_prepare_L4S.py
      - data/raw/L4S
    outs:
      - data/processed/L4S
  A19:
    cmd:
      - python scripts/data_prepare_split.py --src data/raw/A19 --dst data/interim/A19
      - python scripts/data_prepare_png.py --src data/interim/A19 --dst data/processed/A19
      - python scripts/data_prepare_config.py --dataset data/processed/A19
    deps:
      - scripts/data_prepare_split.py
      - scripts/data_prepare_png.py
      - data/raw/A19
    outs:
      - data/processed/A19
  Ischia:
    cmd:
      - python scripts/data_prepare_png.py --src data/raw/Ischia --dst data/processed/Ischia
      - python scripts/data_prepare_config.py --dataset data/processed/Ischia
    deps:
      - scripts/data_prepare_png.py
      - data/raw/Ischia
    outs:
      - data/processed/Ischia