params:
  model: "L4S/unet"
  project: "landslide"
  name: "test"
  dataset: 'data/processed/csv_split/Bella_5cm.yml'
  weights:
  resume: false
  epochs: 100
  lr: 0.0003
  batch_size: 16
  weight_decay: 0.0005
  seed: 1337
  deterministic: false
  criterion: "bce"
  image_sz: 128
  mask_sz: 128
  normalize: false
  monitor: 'valid/loss'
  patience: 30
  mode: 'min'
  conf: 0.5
  workers: 1
  device: 'cpu'
  save_dir: 'runs'
  save_period: -1
  tracker: none
  val: 'test' # dataset validation fold as named in file system
  augment: false
  hsv_h: 0.015 # (float) HSV hue augmentation fraction
  hsv_s: 0.7 # (float) HSV saturation augmentation fraction
  hsv_v: 0.4 # (float) HSV value (brightness) augmentation fraction
  degrees: 0.0 # (float) rotation degrees (+/-)
  translate: 0.1 # (float) translation fraction (+/-)
  scale: 0.5 # (float) scale gain (+/-)
  shear: 0.0 # (float) shear degrees (+/-)
  perspective: 0.0 # (float) perspective fraction (0–0.001 typical)
  flipud: 0.0 # (float) vertical flip probability
  fliplr: 0.5 # (float) horizontal flip probability
  bgr: 0.0 # (float) RGB↔BGR channel swap probability
  mosaic: 1.0 # (float) mosaic augmentation probability
  mixup: 0.0 # (float) MixUp augmentation probability
  cutmix: 0.0 # (float) CutMix augmentation probability
  copy_paste: 0.0 # (float) segmentation copy-paste probability
  copy_paste_mode: flip # (str) copy-paste strategy for segmentation: flip or mixup
  auto_augment: randaugment # (str) classification auto augmentation policy: randaugment, autoaugment, augmix
  erasing: 0.4 # (float) random erasing probability for classification (0–0.9), <1.0
