params:
  model: "L4S/unet"
  project: "landslide"
  name: "test"
  dataset: 'data/processed/csv_split/Bella_5cm.yml'
  weights:
  resume: false
  epochs: 100
  lr: 0.0003
  batch_size: 16
  weight_decay: 0.0005
  seed: 1337
  deterministic: false
  criterion: "bce"
  image_sz: 128
  mask_sz: 128
  normalize: true
  monitor: 'valid/loss'
  patience: 30
  mode: 'min'
  conf: 0.5
  workers: 1
  device: 'cpu'
  save_dir: 'runs'
  save_period: -1
  tracker: none
  val: 'test' # dataset validation fold as named in file system